mend ➜ fixes

diff --git a/bin/spawn b/bin/spawn
--- a/bin/spawn
+++ b/bin/spawn
@@ -4,6 +4,10 @@
 include barg.sh
 include logger.sh
 
+function get_file_hash {
+  ls -lh "${WATCH_PATH}" 2>/dev/null | md5sum | cut -d ' ' -f 1
+}
+
 function time_parse {
   IFS=':' read -r seconds minutes hours days
 
@@ -22,6 +26,25 @@ function time_parse {
   printf '%s %s\n' "${t_sec}" "${t_str}"
 }
 
+function run_on_change {
+  local interval="${1}"
+  shift 1
+
+  read -r LAST_HASH < <(get_file_hash)
+  log i 'Initial hash: %s' "${LAST_HASH}"
+
+  while true; do
+    sleep "${interval}"
+    read -r CURRENT_HASH < <(get_file_hash)
+
+    if [ "${CURRENT_HASH}" != "${LAST_HASH}" ]; then
+      log i '%(%F %T)T: Change detected! %s' -1
+      "${@}"
+      LAST_HASH="${CURRENT_HASH}"
+    fi
+  done
+}
+
 function spawner {
   sleep "${1:?}" || return
   shift 1
@@ -32,15 +55,26 @@ function spawner {
     fi
   fi
 
-  if "${SPAWN_AS_GNOME}"; then
-    XDG_CURRENT_DESKTOP=GNOME XDG_SESSION_DESKTOP=gnome exec "${@}" &> /dev/null
+  ${SPAWN_GO_FS_ROOT} && {
+    cd / &> /dev/null || {
+      log e "Failed to change dir to root (/)" && return
+    }
+  }
+
+  if ${SPAWN_AS_GNOME}; then
+    XDG_CURRENT_DESKTOP=GNOME XDG_SESSION_DESKTOP=gnome \
+      exec "${@}"
   else
-    exec "${@}" &> /dev/null
+    exec "${@}"
   fi
 }
 
 function main {
-  local _epilogs=("{acc}Note:\x1b[0m" "  \`-a/--run-at\` format is: seconds:minutes:hours:days, default: 0:0:0:0)")
+  local _epilogs=(
+    "{acc}Note:\x1b[0m"
+    "  \`-a/--run-at\` format is: seconds:minutes:hours:days, default: 0:0:0:0"
+    "  \`-a/--run-at\` with -w/--watch-file format is the same as sleep command"
+  )
   barg::parse "${@}" << BARG
   #[always]
   meta {
@@ -52,11 +86,17 @@ function main {
   }
 
   r/restart :flag => SPAWN_RESTART "Restart the process if it is already running"
-  a/run-at :str "0:0:0:0" => SPAWN_AT_TIME "Time to wait before spawning the process"
+  c/cwd-root :flag => SPAWN_GO_FS_ROOT "Change PWD / to prevent locking CWD"
+  k/keep :flag true => SPAWN_IN_BACKGROUND "Do not detach from caller terminal"
+  w/watch-file :str => WATCH_PATH "Run when file is updated, --run-at for interval"
+  a/run-at :str "" => SPAWN_AT_TIME "Time to wait before spawning the process"
   g/as-gnome :flag => SPAWN_AS_GNOME "Launch the process as a GNOME session"
   u/uwsm :flag => SPAWN_WITH_UWSM "Spawn process using uwsm"
   L/logger :int 4 => LOGGER_LEVEL "Logging level"
 BARG
+  if [[ -n "${WATCH_PATH}" && ! -e "${WATCH_PATH}" ]]; then
+    barg::exit_msg "Directory not found" "Arg for '-d/--dir-file' must be an existing file or folder"
+  fi
   barg::unload
 
   if ${SPAWN_WITH_UWSM} && ! command -v uwsm &> /dev/null; then
@@ -71,13 +111,20 @@ BARG
 
   ${SPAWN_WITH_UWSM} && {
     SPAWN_EXEC_LINE=("uwsm" "app" "--" "${SPAWN_EXEC_LINE[@]}")
-    ((SPAWN_EXEC_LINE_COUNT+=3))
+    ((SPAWN_EXEC_LINE_COUNT += 3))
   }
 
   ((SPAWN_EXEC_LINE_COUNT > 1)) && printf -v cmd_line ' %q' "${SPAWN_EXEC_LINE[@]:1}"
   local cmd_line="${SPAWN_EXEC_LINE[0]}${cmd_line}"
 
-  read -r t_sec t_str < <(time_parse <<< "${SPAWN_AT_TIME}")
+  log d 'Command to run: %s' "${cmd_line}"
+
+  [ -n "${WATCH_PATH}" ] && {
+    run_on_change "${SPAWN_AT_TIME:-0.5}" "${SPAWN_EXEC_LINE[@]}"
+    return
+  }
+
+  read -r t_sec t_str < <(time_parse <<< "${SPAWN_AT_TIME:-0:0:0:0}")
 
   if ((t_sec > 0)); then
     if ${SPAWN_RESTART}; then
@@ -87,8 +134,11 @@ BARG
     fi
   fi
 
-  log d 'Command to run: %s' "${cmd_line}"
-  spawner "${t_sec}" "${SPAWN_EXEC_LINE[@]}" &
+  ${SPAWN_IN_BACKGROUND} || {
+    spawner "${t_sec}" "${SPAWN_EXEC_LINE[@]}"
+    return
+  }
+  spawner "${t_sec}" "${SPAWN_EXEC_LINE[@]}" &> /dev/null &
 }
 
 main "${@}"
